### ISSUE TITLE
can I run it on my local machine ?!

### ISSUE THREAD

**Issue by othmane53** [tcd93/flutter-pos#11]
hi,
i'm a little new to flutter.. i'm wondering if I can use the code on my local machine ? I tried to do so, by downloading the code but I faced a problem of missing files like " package:flutter_gen/gen_l10n/app_localizations.dart " or " package:provider/provider.dart "
what should I do ?
thanks

**Comment by tcd93** [comment]
you should download [packages](https://flutter.dev/docs/development/packages-and-plugins/using-packages) by running `flutter pub get` first

**Comment by hrokuwait** [comment]
Resource attribute "@main_title" was not found. Please ensure that each resource has a corresponding
@resource.
Generating synthetic localizations package has failed.
this error showing while commit "flutter pub get". what should i do?
