### ISSUE TITLE
Need some Info

### ISSUE THREAD

**Issue by usmanali353** [tcd93/flutter-pos#14]
in Readme you have mentioned that app is Tested and printable on sunmi v1s Devices i have searched about these devices these have built in Printer. Kindly explain  which Flutter package you are using to print through sunmi devices i hsve checked your pubspec.yaml it does not contain any Sunmi sdk package

**Comment by tcd93** [comment]
No I'm not using any printer provider's SDKs, it's just that I have tested this library on Sunmi device and I have printed without problem

I'm using a flutter package called **[blue_thermal_printer](https://github.com/kakzaki/blue_thermal_printer)** actually, it sends bluetooth signals directly to the printing device (those signals follow ECS/POS standard), so any device that is ECS/POS compliant should work, not just Sunmi's

(The *blue_thermal_printer* repo I'm using is a fork of the original, I've modified it a bit to print correctly on a 58mm handheld printer)

**Comment by tcd93** [comment]
If you do use Sunmi printer, what I'm doing is essentially on section 2 page 49 of their [developer's guide](https://file.cdn.sunmi.com/SUNMIDOCS/Sunmi-Printing-Service-ENCN.pdf) - Call a Printer via the
Inbuilt Virtual Bluetooth
