### ISSUE TITLE
Can not run the project

### ISSUE THREAD

**Issue by ramezanzade1** [tcd93/flutter-pos#17]
When I. debug the project, then this error is happening:

* What went wrong:
A problem occurred configuring project ':blue_thermal_printer'.
> Could not resolve all artifacts for configuration ':blue_thermal_printer:classpath'.
   > Could not find bundletool-0.9.0.jar (com.android.tools.build:bundletool:0.9.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.9.0/bundletool-0.9.0.jar
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':blue_thermal_printer' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':blue_thermal_printer' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by tcd93** [comment]
I can not reproduce, you might be having connection issue, VPN?
