### ISSUE TITLE
syncfusion_flutter_datepicker: ^20.3.61

### ISSUE THREAD

**Issue by flutter-painter** [tcd93/flutter-pos#21]
version 22.1.39 is incompatible with previous intl version, please consider lowering it in the yaml

Because every version of flutter_localizations from sdk depends on intl 0.17.0 and syncfusion_flutter_datepicker >=21.2.4 depends on intl ^0.18.0, flutter_localizations from sdk is incompatible with syncfusion_flutter_datepicker >=21.2.4.

**Comment by tcd93** [comment]
Please upgrade to Flutter >=3.10 as of Flutter 3.7 localizations package still depend on intl 0.17

**Comment by flutter-painter** [comment]
Yes but the latest sdk requires full null safety everywhere, which is not possible for procrastinators who prefer focusing on cooler stuff.
Are you using any of the elements in the changelog (screenshot below)?
Else why force users ?

<img width="808" alt="Screenshot 2023-09-05 at 19 44 41" src="https://github.com/tcd93/flutter-pos/assets/14161798/9cecb38e-8da0-4076-9aa3-6cb79d0241c0">
