### ISSUE TITLE
table map instead of random table

### ISSUE THREAD

**Issue by flutter-painter** [tcd93/flutter-pos#23]
Very impressed by the simplicity of your solution, 
I was able to deduce all functionalities with almost no text,
If I may suggest an enhancement regarding the table plan

As a small restaurant own I would rather lay down / draw name my tables and then assign orders to them

Also you might be interested in this UI for meal / beverage selection :
https://github.com/wilsonanyonga/flutter_pos

**Comment by tcd93** [comment]
Thank you.

The current table plan is just what I came up during coding and not really planned beforehand, but it works for me personally as I'd just remember the layout after awhile.

The design from the repo you provided seems better fit for monitor screen / web view.  I will try to add another UI version of this if I have time.
