### ISSUE TITLE
Need more info on what are you trying to achieve 🙂

### ISSUE THREAD

**Issue by keertirajmalik** [tcd93/flutter-pos#7]

**Comment by tcd93** [comment]
What do you mean? This is a side project that I use to learn Flutter. If this also help somebody out then I'm grad.

You're welcome to contribute if you have ideas (UI, UX, features etc...) :)

I realize the codebase's kinda ugly rightnow, I should refactor some of it until it is more readable

I plan to keep updating this until this actually become useful in a real world scenario

**Comment by keertirajmalik** [comment]
At that time readme file only had image so wanted to see what is the app is trying to achieve now that I see you added more info 😊

**Comment by tcd93** [comment]
Great! Thanks for being one of the first visitor haha
